### ISSUE TITLE
Notifications do not reappear after being snoozed. 

### ISSUE THREAD

**Issue by Mignif** [lgariv/Selenium#3]
iPhone 6s, iOS 13.5 (Checkra1n)
UI elements appear as they should, however, when snoozing the notification, it disappears and does not return. (Similar to dismissing it)

**Comment by lgariv** [comment]
There appear to be an issue with permissions on some files stored on the
device. An update will come out in the next few days fixing this and much
more issues, I would suggest you to uninstall selenium completely before
installing the update to make sure everything is working properly.
