### ISSUE TITLE
Selenium Crashing Springboard

### ISSUE THREAD

**Issue by ghost** [lgariv/Selenium#4]
Hey Selenium after updating other tweaks keeps crashing spring board... even if i downgrade those tweaks/stop tweak injection via icleanerpro same result... 

i recently updated dockx and tweaksearch which caused my phone to go into respring loop, then on rejailbreak it could only enter into safe mode because springboard kept crashing... i disabled tweak injection for both and the result kept happening. I thought originally they were to blame but cr4shed shows selenium as the culprit.. on disabling selenium no more safe mode... all back to normal.

Not sure why updating the other two tweaks would then result in selenium crashing springboard... but wanted to let you know... enjoy your tweak.. let me know if you would like the crash log/if this can get resolved so i can use your tweak again!

**Comment by lgariv** [comment]
Hey, a fix will come out in the next few days. In the meantime, I posted a
temporary workaround on my Twitter that solves the problem. 
It is worth mentioning that updating the tweaks is not what caused it. 

Edit:
The temporary workaround is to delete the following folder in Filza:
/var/mobile/Library/Selenium/
