### ISSUE TITLE
Selenium not working with Axon Reborn, also not providing audible notifications

### ISSUE THREAD

**Issue by FirstJohn318** [lgariv/Selenium#6]
So, I go to use the snoozing feature and it lets me snooze it but the notification will not go away from Axon Reborn unless I respring. Also, when the notification comes back there is no audible notification. The notification also does not reappear on my watch (though I feel like that may be a normal thing, not sure). Another thing is the "stepper" doesn’t drop below 15min. I am on iOS 13.5, iPhone 11 Pro, Unc0ver 5.3.1.

**Comment by lgariv** [comment]
Can you provide more info? Axon settings + screen recording of the mentioned behavior?

If you meant to Axon label count not updating right away, that is a known bug.

Also, stepper should not get below 15 minutes. For kore precise control, you can use the "specific time" option, that's what it was made for.
And there shouldn't be any audio when notifications are coming back as well: notifications are hidden and re-appear at the chosen time. 

About watch support: it is an iOS tweak. No reason it would affect your watch.

**Comment by FirstJohn318** [comment]
Was this fixed?

**Comment by FirstJohn318** [comment]
Was this issue fixed?

**Comment by lgariv** [comment]
> Was this fixed?
> 

Read my reply.

**Comment by FirstJohn318** [comment]
You wrote closed but the issue was still there. Was wondering if there was an update that you haven’t released yet

**Comment by lgariv** [comment]
> You wrote closed but the issue was still there. Was wondering if there was an update that you haven’t released yet
> 
> > On Sep 2, 2020, at 01:29, Lavie <notifications@github.com> wrote:
> > 
> > ﻿
> > Was this fixed?
> > 
> > On Aug 29, 2020, at 13:02, Lavie notifications@github.com wrote:
> > 
> > ﻿
> > Closed #6.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > Read my reply.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 

I asked you to provide more info and a screen recording. You completely ignored my request.
I answered all of your questions in my first reply, just... read it.

**Comment by FirstJohn318** [comment]
Yes…I sent you two pictures and a screen recording, I did not ignore your request. I will forward you the email again…but here is a screenshot with the timestamp…
