### ISSUE TITLE
Selemium Crashing w/Axon Reborn clear notifications

### ISSUE THREAD

**Issue by ghost** [lgariv/Selenium#7]
Crashing when long pressing on notification to clear notifications with clear all as part of axon reborn 
Video attached as well as crash log

Log - https://hastebin.com/ugavefogec.sql
Video - https://drive.google.com/file/d/1L_i4dkuaMTZXQ_kVcOt4crwPMDrE3cwu/view?usp=sharing

**Comment by lgariv** [comment]
That is a known issue, check the tweak depiction on Dynastic repo.

**Comment by ghost** [comment]
Cant see known issues cause on build from github sry

**Comment by lgariv** [comment]
Solved in the latest commit, will be released as part of release v1.1.2
