### ISSUE TITLE
不支持ios14系统的设备

### ISSUE THREAD

**Issue by pengyam** [lgariv/Selenium#8]
谢谢作者的分享❤️❤️，但是不支持ios14及以上系统的机子，请问能更新到支持ios14系统吗？

**Comment by lgariv** [comment]
> 谢谢作者的分享❤️❤️，但是不支持ios14及以上系统的机子，请问能更新到支持ios14系统吗？

I don't speak Chinese (unfortunately), but an update for iOS 14 will come soon. [Follow me on Twitter](www.twitter.com/lgarivdev) to know as soon as it is released.

**Comment by pengyam** [comment]
Thank you 🌹🌹🌹
